name: Docker

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}

        steps:
            - name: Get Tag
              run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

            - name: Checkout
              uses: actions/checkout@v4

            - name: Build Docker Image
              run: docker build -t bryanc12/urllinker_backend:${{ env.TAG }} .

            - name: Login to Docker Hub
              run: docker login -u bryanc12 -p ${{ secrets.DOCKER_HUB_KEY }}

            - name: Push Docker Image
              run: docker push bryanc12/urllinker_backend:${TAG}
