name: Docker

on:
    push:
        tags:
            - v*.*.*

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        if: github.ref

        steps:
            - name: Echo Ref
              run: echo "${{ github.ref }}"
